name: Release

# Only trigger when a pull request into main branch is merged.
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2

      - name: Check pyproject.toml file
        run: poetry check

      - name: Install package
        run: poetry install

      - name: Run tests
        env:
          NEO4J_PASSWORD: this-will-not-work
          NEO4J_URI: neo4j+s://some-database.neo4j.io
          NEO4J_USERNAME: this-will-not-work
        run: poetry run python -m unittest

  release:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2

      - name: Check pyproject.toml file
        run: poetry check

      - name: Get package version
        id: get-package-version
        run: echo "package_version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
        with:
          tag_name: ${{ steps.get-package-version.outputs.package_version }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

  publish:
    needs: release
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.2

      - name: Build a binary wheel and a source tarball
        run: poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
